[project]
name = "rhapsode"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "google-genai",
    "python-dotenv",
    "chromadb",
    "sentence-transformers",
]

[tool.setuptools.packages.find]
include = ["rhapsode*"]

[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"
