from rhapsode import _core


def test_public_binding_surface_is_stable():
    expected = {
        "Annotator",
        "Character",
        "CharacterMemory",
        "DeathCandidate",
        "Director",
        "DirectorOutput",
        "EdgeData",
        "EdgeInfo",
        "EntitySpan",
        "ExpiryOp",
        "GraphAnalysis",
        "History",
        "LoopState",
        "MemorySystem",
        "Node",
        "NodeState",
        "Rejection",
        "Role",
        "Scene",
        "SceneLoop",
        "SceneMessage",
        "Snippet",
        "Story",
        "TextDownsampler",
        "WeaveOp",
        "WeaveResult",
        "Weaver",
        "World",
        "WorldGraph",
        "analyze_graph",
    }

    assert {name for name in dir(_core) if not name.startswith("_")} == expected


def test_runtime_class_method_surfaces_are_stable():
    expected = {
        "SceneLoop": {
            "join_background",
            "last_director_output",
            "last_weave_result",
            "load_scene",
            "set_director",
            "set_history_window",
            "set_llm_callback",
            "set_narrator_llm_callback",
            "set_resuming",
            "set_saves_dir",
            "set_turn_complete_callback",
            "set_weaver",
            "state",
            "submit_autonomous",
            "submit_input",
            "take_completed_expiry_ops",
            "take_last_turn_outputs",
        },
        "Story": {
            "active_scene",
            "active_scene_id",
            "advance_scene",
            "apply_pending_ops",
            "beat_clock",
            "bind_runtime",
            "conclude_scene",
            "delete_save",
            "dispatch_tool",
            "fork_scene",
            "from_scene",
            "get_scene",
            "has_save",
            "load_save",
            "merge_scene",
            "note_advanced",
            "save",
            "scene_count",
            "scene_ids",
            "set_downsampler_callback",
            "set_lifecycle_callback",
            "set_saves_dir",
            "set_scheduler_callback",
            "tool_list_scenes",
            "world",
        },
        "World": {
            "character_memories",
            "characters",
            "clear_pending_ops",
            "find_character",
            "has_save",
            "load_save",
            "save",
            "scan_death_candidates",
            "set_reflection_llm_callback",
            "set_memory",
            "stage_conclude",
            "stage_exit",
            "stage_fork",
            "stage_merge",
            "tool_query_graph",
            "tool_query_mind",
            "world_graph",
        },
        "Scene": {
            "character_memories",
            "characters",
            "charge",
            "delete_save",
            "dialogue",
            "display_timeline",
            "downsampler",
            "driving_intention",
            "enter_character",
            "exit_character",
            "find_on_stage",
            "fork",
            "from_json_str",
            "has_save",
            "history",
            "last_advanced",
            "load_json",
            "load_save",
            "revert_turns",
            "save",
            "save_json",
            "scan_death_candidates",
            "scene_id",
            "set_memory",
            "system_prompt",
            "title",
            "to_json_str",
            "tool_query_graph",
            "tool_query_history",
            "tool_query_mind",
            "turn_index",
            "world",
            "world_graph",
        },
    }

    for class_name, methods in expected.items():
        cls = getattr(_core, class_name)
        assert {name for name in dir(cls) if not name.startswith("_")} == methods
